version: '2'
services:
  db:
    image: postgres
  datastore:
    build: datastore
  cache:
    image: redis
  app:
    build: .
    environment:
      RAILS_ENV: production
      NODE_ENV: production
    env_file: .env
    command: bundle exec rails s -b '0.0.0.0' -p 5555
    volumes:
      - .:/TEE
    ports:
      - 5555:5555
    depends_on:
      - db
      - cache
    volumes_from:
      - datastore
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    volumes_from:
      - datastore
