version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./docker/postgres.dev:/var/lib/postgresql/data
  cache:
    image: redis
  app:
    build: .
    env_file: .env
    command: bundle exec rails s -p 5555 -b '0.0.0.0'
    environment:
      RAILS_ENV: production
      NODE_ENV: production
    volumes:
      - .:/TEE
    ports:
      - 5555:5555
    depends_on:
      - db
      - cache
