development: &default
  adapter: postgresql
  encoding: unicode
  database: TEE_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: TEE_test
production:
  <<: *default
  database: TEE_production
