default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TEE_development

test:
  <<: *default
  database: TEE_test

production:
  <<: *default
  hosts: <%= ENV['TEE_PRODUCTION_HOST'] %>
  database: TEE_production
  username: TEE
  password: <%= ENV['TEE_DATABASE_PASSWORD'] %>
